import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class Vgenerator extends Thread{
	private int x;
	private int y;
	private String symbol;
	private Intersection intersection;
	private int generateSpeed;
	private String direction;
	private int spec;
	private boolean signal;
	private List<Car> carList;	//hold the car generated by the generator
	private double overallTime;	//record the time the car traveling through the grid

	
	public Vgenerator(Intersection intersection,String symbol,int speed,String direction,int spec) {
		this.intersection=intersection;
		this.symbol=symbol;
		this.generateSpeed=speed;
		this.direction=direction;
		this.spec=spec;
		carList=new ArrayList<>();		
	}
	
	/**
	 * generate car from north to south or from south to north
	 * It is up to the choice of the main method(APSpec1 or APSpec2)
	 * @return
	 */
	public Car generateCar() {
		Random ran=new Random();
		int rowBoundary=intersection.getRows(); 
		int colBoundary=intersection.getColumns();
		Car geCar=null;
		if(spec==1) {
			y=ran.nextInt(colBoundary);
			x=0;
			geCar=new Car(x,y,symbol,intersection,direction);
		}	
		else if(spec==2) {
			switch(direction) {
			case "NS":
				y=ran.nextInt(colBoundary/2);
				x=0;
				break;
			case "SN":
				y=ran.nextInt(colBoundary/2)+colBoundary/2;
				x=rowBoundary-1;
				break;
			}
			geCar=new Car(x,y,symbol,intersection,direction);
		}
		return geCar;	
	}
	
	public void run() {
		//keep running until receiving the signal to stop 
		while(!intersection.isSignal()) {
			try {
				sleep(generateSpeed);
			}catch(InterruptedException e) {
				e.printStackTrace();
			}
			startCar();
		}	
		getSumTravelTime(); 
	}
	
	/**
	 *start the car thread
	 */
	public void startCar() {
		Car geCar=generateCar();
		carList.add(geCar);	//after generating a car, add it to the car list
		geCar.addCar();
		geCar.start();
	}
	
	private void getSumTravelTime() {
		for(Car car:carList) {
		overallTime=car.getGridTime()+overallTime;
		}
	}

	public List<Car> getCarList() {
		return carList;
	}

	public void setCarList(List<Car> carList) {
		this.carList = carList;
	}

	public String getDirection() {
		return direction;
	}

	public boolean isSignal() {
		return signal;
	}

	public void setSignal(boolean signal) {
		this.signal = signal;
	}

	public double getOverallTime() {
		return overallTime;
	}

	public void setOverallTime(double overallTime) {
		this.overallTime = overallTime;
	}
}
